### ISSUE TITLE
Paypalbutton einbinden beim Spenden

### ISSUE THREAD

**Issue by koos** [railslove/startups-fuer-fortuna.github.io#11]
Wenn der User via Paypal bezahlen möchte könnte man einen ofiziellen Button einbinden auf /donations

**Comment by nerdbabe** [comment]
https://www.paypal.com/de/cgi-bin/webscr?cmd=_flow&SESSION=2G_ed3jOHw__SEi1fUCDZaabpMDrOTc75sXMPGrMROJ6D8EyPRsI5Ju2KGu&dispatch=5885d80a13c0db1f8e263663d3faee8de6030e9239419d79c3f52f70a3ed57ec

Welcher Button soll es denn sein? Den Spendenbutton darf man nur verwenden, wenn man eine gemeinnützige Vereinigung ist:
Hinweis: Dieser Button ist für das Sammeln von Spenden vorgesehen. Wenn Sie keine Spenden sammeln, wählen Sie eine andere Option. Gemeinnützige Organisationen müssen ihren Status verifizieren, um erhaltene Spenden abzubuchen. Nutzer, die keine verifizierten gemeinnützigen Organisationen sind, müssen darlegen, wie die Spenden verwendet werden, sobald sie mehr als 10.000 USD sammeln.

Soll der Paypalbutton dann den grünen Spenden-Button ersetzen auf der Seite?

**Comment by koos** [comment]
Ne dann passts

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.4.27&pv=8.3]
On Mo., Juli 6, 2015 at 3:41 nachm., Ute Mayer <notifications@github.com> wrote:

https://www.paypal.com/de/cgi-bin/webscr?cmd=_flowSESSION=2G_ed3jOHw__SEi1fUCDZaabpMDrOTc75sXMPGrMROJ6D8EyPRsI5Ju2KGu&dispatch=5885d80a13c0db1f8e263663d3faee8de6030e9239419d79c3f52f70a3ed57ec]

Welcher Button soll es denn sein? Den Spendenbutton darf man nur verwenden, wenn
man eine gemeinnützige Vereinigung ist:
Hinweis: Dieser Button ist für das Sammeln von Spenden vorgesehen. Wenn Sie
keine Spenden sammeln, wählen Sie eine andere Option. Gemeinnützige
Organisationen müssen ihren Status verifizieren, um erhaltene Spenden
abzubuchen. Nutzer, die keine verifizierten gemeinnützigen Organisationen sind,
müssen darlegen, wie die Spenden verwendet werden, sobald sie mehr als 10.000
USD sammeln.

Soll der Paypalbutton dann den grünen Spenden-Button ersetzen auf der Seite?

—
Reply to this email directly or view it on GitHub
[https://github.com/railslove/startups-fuer-fortuna.github.io/issues/11#issuecomment-118857084] .[https://github.com/notifications/beacon/AAAgl3tbDQW1IA8PUxQ6v3NAIh0J3LQ-ks5oan0JgaJpZM4FR7_H.gif]
